### ISSUE TITLE
byte where error occured

### ISSUE THREAD

**Issue by shawnl** [cyb70289/utf8#3]
I need this, and will probably add it if you do not.

**Comment by cyb70289** [comment]
Hi Shawn,

Thanks for your interest in this code. Locating where error occurs is a useful feature. I have the plan, maybe in this month, cannot guarantee.
You are welcomed to implement it (and even greater if you can contribute your code :)

Yibo

**Comment by cyb70289** [comment]
Commit https://github.com/cyb70289/utf8/commit/1b52b9699947674be4d0e997baba0928ddd6f780
added returning index of first error char to naive.c and range-sse.c.
define RET_ERR_IDX to 1 to enable it. See https://github.com/cyb70289/utf8/blob/master/range-sse.c#L81.
