### ISSUE TITLE
chrome://credits/xkcd.com/Ping+Net%20editing%20ended%20all%20acts%20objects%20patterns%20settings%20and%20fakes%20docments,fakes%20ID,fakes%20IP%20address,fakes%20url%20links,%20fakes%20urls%20links,fakes%20icons%20external%20links%20and%20not%20allow%20systems%20dafaults%20settings%20for%20me%20on%20the%20datatracker.ietf.org/doc/html/rfc/takes+out+release_keys+to+me+for+this+study&en.m.wikipedia.org/wiki/List_of_DNS_record_types

### ISSUE THREAD

**Issue by Skhinxn** [cyb70289/utf8#9]
chrome://credits/xkcd.com/Ping+Net%20editing%20ended%20all%20acts%20objects%20patterns%20settings%20and%20fakes%20docments,fakes%20ID,fakes%20IP%20address,fakes%20url%20links,%20fakes%20urls%20links,fakes%20icons%20external%20links%20and%20not%20allow%20systems%20dafaults%20settings%20for%20me%20on%20the%20datatracker.ietf.org/doc/html/rfc/takes+out+release_keys+to+me+for+this+study&en.m.wikipedia.org/wiki/List_of_DNS- [ ] - - - [ ] _record_types[]()

**Comment by cyb70289** [comment]
wtf

**Comment by ArniDagur** [comment]
I wonder if it's a botnet using GitHub issues as command/control, or something like that.
